/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mealplanning;

import javax.swing.JOptionPane;

/**
 *
 * @author MatheusIFPR
 */
public class Nova_Receita extends javax.swing.JFrame {
     int pesos[] = new int[15];
     String nomes[] = new String[15];
    /**
     * Creates new form Nova_Receita
     */
    public Nova_Receita() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTelaInicial1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        txtIngredientes1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNomeReceita = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnTelaInicial2 = new javax.swing.JButton();
        btnEnviar = new javax.swing.JButton();
        txtPeso1 = new javax.swing.JTextField();
        txtPeso2 = new javax.swing.JTextField();
        txtPeso3 = new javax.swing.JTextField();
        txtPeso4 = new javax.swing.JTextField();
        txtPeso5 = new javax.swing.JTextField();
        txtPeso6 = new javax.swing.JTextField();
        txtPeso7 = new javax.swing.JTextField();
        txtPeso8 = new javax.swing.JTextField();
        txtPeso9 = new javax.swing.JTextField();
        txtPeso10 = new javax.swing.JTextField();
        txtPeso11 = new javax.swing.JTextField();
        txtPeso12 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtPeso13 = new javax.swing.JTextField();
        txtPeso14 = new javax.swing.JTextField();
        txtPeso15 = new javax.swing.JTextField();
        txtNome1 = new javax.swing.JTextField();
        txtNome2 = new javax.swing.JTextField();
        txtNome3 = new javax.swing.JTextField();
        txtNome4 = new javax.swing.JTextField();
        txtNome5 = new javax.swing.JTextField();
        txtNome6 = new javax.swing.JTextField();
        txtNome7 = new javax.swing.JTextField();
        txtNome8 = new javax.swing.JTextField();
        txtNome9 = new javax.swing.JTextField();
        txtNome10 = new javax.swing.JTextField();
        txtNome11 = new javax.swing.JTextField();
        txtNome12 = new javax.swing.JTextField();
        txtNome13 = new javax.swing.JTextField();
        txtNome14 = new javax.swing.JTextField();
        txtNome15 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        btnLimpar = new javax.swing.JButton();

        btnTelaInicial1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnTelaInicial1.setText("Voltar a Tela Inicial");
        btnTelaInicial1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTelaInicial1ActionPerformed(evt);
            }
        });

        jButton1.setText("jButton1");

        txtIngredientes1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIngredientes1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Nova Receita");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Digite o nome da receita");

        txtNomeReceita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeReceitaActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("Digite os ingredientes");

        btnTelaInicial2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnTelaInicial2.setText("Voltar a Tela Inicial");
        btnTelaInicial2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTelaInicial2ActionPerformed(evt);
            }
        });

        btnEnviar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnEnviar.setText("Enviar");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });

        txtPeso12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPeso12ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Gramas:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Nome:");

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("1 colher de sopa equivale a 15 g.\n1 colher de chá equivale a 5 g.\n1 ovo pequeno 38 g.\n1 ovo médio 44 g.\n1 ovo grande 50 g.\n1 maça média 150 g.\n1 banana média 100 g.");
        jScrollPane1.setViewportView(jTextArea1);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Dicas sobre Medidas:");

        btnLimpar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtPeso15, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPeso14, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPeso13, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPeso2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPeso6, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPeso7, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPeso8, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPeso12, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPeso11, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPeso10, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPeso9, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtPeso1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPeso3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPeso4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPeso5, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNome1)
                            .addComponent(txtNome2)
                            .addComponent(txtNome3)
                            .addComponent(txtNome4)
                            .addComponent(txtNome5)
                            .addComponent(txtNome6)
                            .addComponent(txtNome7)
                            .addComponent(txtNome8)
                            .addComponent(txtNome9)
                            .addComponent(txtNome10)
                            .addComponent(txtNome11)
                            .addComponent(txtNome12)
                            .addComponent(txtNome13)
                            .addComponent(txtNome14)
                            .addComponent(txtNome15)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnEnviar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnTelaInicial2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtNomeReceita)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnLimpar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPeso1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNome1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPeso2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNome2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPeso3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNome3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPeso4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNome4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPeso5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNome5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(txtNomeReceita, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(btnEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnTelaInicial2)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPeso6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNome6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPeso7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNome7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPeso8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNome8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPeso9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNome9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPeso10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNome10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPeso11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNome11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPeso12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNome12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPeso13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNome13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPeso14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNome14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPeso15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNome15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeReceitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeReceitaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeReceitaActionPerformed

    private void btnTelaInicial1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTelaInicial1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTelaInicial1ActionPerformed

    private void btnTelaInicial2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTelaInicial2ActionPerformed
        // TODO add your handling code here:
        Tela_Inicial objTelaInicial = new Tela_Inicial();
        objTelaInicial.setVisible(true);
    }//GEN-LAST:event_btnTelaInicial2ActionPerformed

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        // TODO add your handling code here:
        //GRAMAS
        pesos[0] = Integer.parseInt(txtPeso1.getText());
        pesos[1] = Integer.parseInt(txtPeso2.getText());
        pesos[2] = Integer.parseInt(txtPeso3.getText());
        pesos[3] = Integer.parseInt(txtPeso4.getText());
        pesos[4] = Integer.parseInt(txtPeso5.getText());
        pesos[5] = Integer.parseInt(txtPeso6.getText());
        pesos[6] = Integer.parseInt(txtPeso7.getText());
        pesos[7] = Integer.parseInt(txtPeso8.getText());
        pesos[8] = Integer.parseInt(txtPeso9.getText());
        pesos[9] = Integer.parseInt(txtPeso10.getText());
        pesos[10] = Integer.parseInt(txtPeso11.getText());
        pesos[11] = Integer.parseInt(txtPeso12.getText());
        pesos[12] = Integer.parseInt(txtPeso13.getText());
        pesos[13] = Integer.parseInt(txtPeso14.getText());
        pesos[14] = Integer.parseInt(txtPeso15.getText());
        
        //NOMES:
        nomes[0] = txtNome1.getText();
        nomes[1] = txtNome2.getText();
        nomes[2] = txtNome3.getText();
        nomes[3] = txtNome4.getText();
        nomes[4] = txtNome5.getText();
        nomes[5] = txtNome6.getText();
        nomes[6] = txtNome7.getText();
        nomes[7] = txtNome8.getText();
        nomes[8] = txtNome9.getText();
        nomes[9] = txtNome10.getText();
        nomes[10] = txtNome11.getText();
        nomes[11] = txtNome12.getText();
        nomes[12] = txtNome13.getText();
        nomes[13] = txtNome14.getText();
        nomes[14] = txtNome15.getText();
        
        JOptionPane.showMessageDialog(null, "Enviado com Sucesso!");
        
        Lista_de_Compra listaDeCompras = new Lista_de_Compra(pesos, nomes);
        listaDeCompras.setVisible(true);
        

        //
        
       
        
    }//GEN-LAST:event_btnEnviarActionPerformed

    
    private void txtIngredientes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIngredientes1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIngredientes1ActionPerformed

    private void txtPeso12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPeso12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPeso12ActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        // TODO add your handling code here:
        
        // Nome
        
        txtNome1.setText(" ");
        txtNome2.setText(" ");
        txtNome3.setText(" ");
        txtNome4.setText(" ");
        txtNome5.setText(" ");
        txtNome6.setText(" ");
        txtNome7.setText(" ");
        txtNome8.setText(" ");
        txtNome9.setText(" ");
        txtNome10.setText(" ");
        txtNome11.setText(" ");
        txtNome12.setText(" ");
        txtNome13.setText(" ");
        txtNome14.setText(" ");
        txtNome15.setText(" ");
        
        // Peso
        
        txtPeso1.setText(" ");
        txtPeso2.setText(" ");
        txtPeso3.setText(" ");
        txtPeso4.setText(" ");
        txtPeso5.setText(" ");
        txtPeso6.setText(" ");
        txtPeso7.setText(" ");
        txtPeso8.setText(" ");
        txtPeso9.setText(" ");
        txtPeso10.setText(" ");
        txtPeso11.setText(" ");
        txtPeso12.setText(" ");
        txtPeso13.setText(" ");
        txtPeso14.setText(" ");
        txtPeso15.setText(" ");
        
        // Nome da Receita
        
        txtNomeReceita.setText(" ");
                
    }//GEN-LAST:event_btnLimparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Nova_Receita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Nova_Receita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Nova_Receita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Nova_Receita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Nova_Receita().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnTelaInicial1;
    private javax.swing.JButton btnTelaInicial2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField txtIngredientes1;
    private javax.swing.JTextField txtNome1;
    private javax.swing.JTextField txtNome10;
    private javax.swing.JTextField txtNome11;
    private javax.swing.JTextField txtNome12;
    private javax.swing.JTextField txtNome13;
    private javax.swing.JTextField txtNome14;
    private javax.swing.JTextField txtNome15;
    private javax.swing.JTextField txtNome2;
    private javax.swing.JTextField txtNome3;
    private javax.swing.JTextField txtNome4;
    private javax.swing.JTextField txtNome5;
    private javax.swing.JTextField txtNome6;
    private javax.swing.JTextField txtNome7;
    private javax.swing.JTextField txtNome8;
    private javax.swing.JTextField txtNome9;
    private javax.swing.JTextField txtNomeReceita;
    private javax.swing.JTextField txtPeso1;
    private javax.swing.JTextField txtPeso10;
    private javax.swing.JTextField txtPeso11;
    private javax.swing.JTextField txtPeso12;
    private javax.swing.JTextField txtPeso13;
    private javax.swing.JTextField txtPeso14;
    private javax.swing.JTextField txtPeso15;
    private javax.swing.JTextField txtPeso2;
    private javax.swing.JTextField txtPeso3;
    private javax.swing.JTextField txtPeso4;
    private javax.swing.JTextField txtPeso5;
    private javax.swing.JTextField txtPeso6;
    private javax.swing.JTextField txtPeso7;
    private javax.swing.JTextField txtPeso8;
    private javax.swing.JTextField txtPeso9;
    // End of variables declaration//GEN-END:variables
}
